<?php


/**
 * Implementation hook_quiz_finished().
 *
 * Performs actions like sending quiz results over email at the end of quiz.
*/
function quiz_rules_quiz_finished($quiz, $score, $rid) {
global $user;
  if (module_exists('rules')) {
    $taker = user_load($user->uid);
    $author = user_load($quiz->uid);
    $quiz = node_load($quiz->nid);

    rules_invoke_event('quiz_rules_quiz_taken', $taker, $author, $quiz);
    
    if ($score['percentage_score'] >= $quiz->pass_rate) {
      rules_invoke_event('quiz_rules_quiz_passed', $taker, $author, $quiz);
    }
    if ($score['percentage_score'] < $quiz->pass_rate) {
      rules_invoke_event('quiz_rules_quiz_failed', $taker, $author, $quiz);
    }
  } 
} 