<?php
/**
 * Implements hook_menu().
 *
 * Add an administration page for testing and setting variables about the
 * LimeSurvey synchronization.
 */
function limesurvey_sync_menu() {
  return array(
    'admin/config/ls_sync' => array(
      'title' => 'LimeSurvey Sync',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('limesurvey_sync_survey_admin_form'),
      'access arguments' => array('set limesurvey synchronization'),
      'type' => MENU_NORMAL_ITEM,
      'weight' => 0,
      'file' => 'limesurvey_sync.admin.inc',
    ),
  );
}

/**
 * Implements hook_permission().
 *
 * Define a permission to allow users to access to the module administration
 * page.
 */
function limesurvey_sync_permission() {
  return array(
    'set limesurvey synchronization' => array(
      'title' => t('set LimeSurvey synchronization'),
      'description' => t('To configure the synchronization between your LimeSurvey site and this Drupal site'),
    ),
  );
}

/**
 * Implements hook_enable().
 *
 * Display message on enabling the limesurvey_sync module
 */
function limesurvey_sync_enable() {
  drupal_set_message(t('LimeSurvey Sync module enabled'));
  drupal_set_message(t('In order to set synchronization between Drupal and LimeSurvey, go under <a href="@url">Administer > Site configuration > LimeSurvey Sync</a>',
    array('@url' => url('admin/config/ls_sync'))
  ));
}

/**
 * Implements hook_disable().
 *
 * Display messages on disabling the limesurvey_sync module
 */
function limesurvey_sync_disable() {
  drupal_set_message(t("LimeSurvey Sync module disabled"));
}
